### ISSUE TITLE
License & IP Rights

### ISSUE THREAD

**Issue by mangoplane** [zkemail/email-wallet#50]
Hey there,

First of all, great work with ZK Email. I'm curious if the MIT license applies to all IP that the repository conveys, in addition to the code. I was hoping to make a fork and get to work supporting Algorand (no promises). It would be great if you could just clarify whether I could proceed to do that without concerns for IP infringement of any kind.

I think @SoraSuegami is the original proposer of the method in their paper.

Cheers!

**Comment by Divide-By-0** [comment]
> Hey there,
> 
> First of all, great work with ZK Email. I'm curious if the MIT license applies to all IP that the repository conveys, in addition to the code. I was hoping to make a fork and get to work supporting Algorand (no promises). It would be great if you could just clarify whether I could proceed to do that without concerns for IP infringement of any kind.
> 
> I think @SoraSuegami is the original proposer of the method in their paper.
> 
> Cheers!

We'd be happy to support this kind of work! We do think you'd probably be accelerated if we can help you with understanding the nuances and migrating, and we are happy to help provide that support. Dm me your discord username on telegram yush_g, and we can make a groupchat where you can ask questions if things aren't working? We aren't sure what you mean by all IP other than the code, since the IP is the code here haha and the research paper is already published.

Broadly, we'd definitely appreciate communication! Specifically in terms of the name, we'd prefer if folks changed the name/branding so it's less confusing for users for instance. We'd also love for forks to give back to public goods (i.e. our gitcoin grant) if things go well for you, so we can keep supporting you by fixing bugs you point out, or helping you add features your users would find useful!

It's definitely an experiment in trust from our side to over-trust the community -- as long as we see forks contributing back where they can and acting reasonably, we'll keep things as open as possible :)
